---
- name: "Test case for issue unicode"
  hosts: first
  tasks:
   - debug:
       msg: "Ansible est ÉLÉGANT!"
   - name: "Error when using -v"
     command: echo -e "\xe2\x98\xba\x0a"
   - name: "Error with élégant name"
     debug: msg="Hello world!"
